### ISSUE TITLE
IRC Channel 

### ISSUE THREAD

**Issue by compleatang** [dpp/lawyersongithub#42]
Thought it may be fun to have an IRC channel and to deploy BillingsBot, a legally aware Hubot (not yet deployed). 

If anyone wants to hack on something, may be cool to link the bot to Open Law APIs or something like that. Example, BillingsBot get me the legislative history of PubLaw XYZ. Perhaps no interest or time, but thought I'd propose. 
# lawyersongithub  on Freenode.

**Comment by dogweather** [comment]
A little late here, but I'm down for helping out. I once did something similar, connecting to an api for oregonlaws.org i was playing around with making:

![lawrobot-screenshot](https://cloud.githubusercontent.com/assets/150670/6224774/75e440e2-b636-11e4-92cf-bceb7a16e4b2.jpg)

**Comment by dazzaji** [comment]
is this happening?  because i love it :-)
